### ISSUE TITLE
A request to speak this plugin translated into Chinese

### ISSUE THREAD

**Issue by extrant** [wolfcomp/DeepDungeonDex#12]
I searched for this DeepDungeon plugin, and then I found this plugin very useful.
But my English level is not very good, I think there are many people like me. So I want to talk about some content of this plugin translated into Chinese. But I don't know where the text content of this plugin is displayed, is it in DataHandler.cs? Then it is how to build the source code into a Dalamud plugin. I'm a player, not a programmer, so I'm asking for your help.

I am very sorry, I use translation software to communicate, and there may be some ambiguities caused by the grammatical problems of the translation software. I hope you can understand.

**Comment by wolfcomp** [comment]
My plan is to later add in options to have the entire plugin able to be translated and not hard coded in English.

**Comment by extrant** [comment]
Thanks for your hard work and Looking forward to your update!

**Comment by wolfcomp** [comment]
This is fully implemented with fc97e4d
