### ISSUE TITLE
[Fix]: Data for Orthos Thanatos

### ISSUE THREAD

**Issue by KyonKyonxox** [wolfcomp/DeepDungeonDex#124]
### Mob Id

12107

### What threat level sould the mob have

Easy

### What agro type does the mob have

Sound

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

**Comment by KyonKyonxox** [comment]
The change is to the type of agro the mob has. I stood directly in front of it with RP walk toggled on and got no agro.

**Comment by wolfcomp** [comment]
Need a screenshot as proof as I have multiple sources saying it's sight and not sound

**Comment by KyonKyonxox** [comment]
![Screenshot_30](https://user-images.githubusercontent.com/106009050/231542820-ad616d86-91ed-4804-a300-9b2b975afa4c.png)

I can try and get a fuller screen if you also need the RP buff in the screenshot

**Comment by wolfcomp** [comment]
That is outside the cone for sight.

**Comment by KyonKyonxox** [comment]
Ok I'll go in there and get a better one of me right in front

**Comment by KyonKyonxox** [comment]
![05](https://user-images.githubusercontent.com/106009050/231556603-e683639e-37ed-4784-afad-9393a11dd7a0.png)
![01](https://user-images.githubusercontent.com/106009050/231556617-ee13b25b-8b57-49c3-af45-75850737ddc6.png)
![02](https://user-images.githubusercontent.com/106009050/231556627-c81c13b6-fcce-47f9-a22f-88fa73e725aa.png)
![03](https://user-images.githubusercontent.com/106009050/231556633-0fe01fc7-c544-49de-856a-6774aa64eb4c.png)
![04](https://user-images.githubusercontent.com/106009050/231556640-198a8fbc-b334-490d-ae18-46ab95e715bd.png)

**Comment by KyonKyonxox** [comment]
I managed to get a video of it as well
https://youtu.be/M2xsZGq1Uo4
Video starts with rp walk toggled on. Around 0:19 I turn off rp walk and take a step. The Thanatos has its back to me, but still agros
