### ISSUE TITLE
[Fix]: Data for Orthos Banshee

### ISSUE THREAD

**Issue by Othelia-Emeraldsong** [wolfcomp/DeepDungeonDex#135]
### Mob Id

unsure, sorry T_T I was rushed on time and opened this after clearing the floors

### What threat level sould the mob have

Easy

### What agro type does the mob have

Proximity

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

**Comment by wolfcomp** [comment]
Recheck with having mob id visual active and i might look at it again.
