### ISSUE TITLE
[Fix]: Data for Deep Palace Sprite

### ISSUE THREAD

**Issue by daariasre** [wolfcomp/DeepDungeonDex#136]
### Mob Id

No idea (pls read below)

### What threat level sould the mob have

Easy

### What agro type does the mob have

Sound

### Vulnerabilities for the enemy

- [X] Stun
- [ ] Heavy
- [X] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

### Additional mob text guide

Deep Dungeon Compendium (DD Compendium) does a great job of having everything on a table like the one you see here for floors 101-110 (PotD). Some info is missing from your plugin or wrong (for example the Deep Palace Sprite being Proximity on the plugin data). The Palace Sprite (floors 1-10) is also sound and the one at 181-190 is sight!

I don't know the ID for the sprites nor will I search it because it's not a hard mob so Idc if it's wrong... but checking the compendium will make your amazing plugin better.

https://www.ddcompendium.com/potd_floorsets/101.html

**Comment by wolfcomp** [comment]
Recheck with having mob id visual active and i might look at it again.
