### ISSUE TITLE
[Fix]: Data for Deep Palace Knight

### ISSUE THREAD

**Issue by ayakosaso** [wolfcomp/DeepDungeonDex#139]
### Mob Id

no idea but it's the Deep Palace Knight on floor 191-200

### What threat level sould the mob have

Dangerous

### What agro type does the mob have

Proximity

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

### Additional mob text guide

The Deep Palace Knight is an **undead** mob that **cannot be stunned**. The dex has it listed as stunnable and not showing undead.

I have encountered it today and took a screenshot showing the mob vulnerability:
[https://cdn.discordapp.com/attachments/659904993247100949/1101625220449701941/image.png](url)

**Comment by wolfcomp** [comment]
Recheck with having mob id visual active and i might look at it again.
