### ISSUE TITLE
[Bug]: Debug Window regarding translations opens on start, breaking the plugin

### ISSUE THREAD

**Issue by korriganwhelan** [wolfcomp/DeepDungeonDex#151]
### Dalamud log

Nothing in the console. 

### Steps to reprduce

unknown. Occured when game was started.

### Environment

```markdown
- **OS**: Windows 10
- **Dalamud**: v7.11.0.0
```

### Anything else?

I'm sorry that I can't provide more informations. The plugin just doesnt show any informations anymore, just the box with "floor help" and that's it. 

![Screenshot 2023-09-05 095438](https://github.com/wolfcomp/DeepDungeonDex/assets/43263833/cce3135b-7344-4ec4-a74a-222e0940ae30)

**Comment by wolfcomp** [comment]
Already fixed with 2.7.1 which is in the review queue
