### ISSUE TITLE
[Bug]: Error Codes outside of DeepDungeon

### ISSUE THREAD

**Issue by ZyRage** [wolfcomp/DeepDungeonDex#173]
### Dalamud log

As this is apparently an intended behavior can we get an option to disable this?
That's unnecessary space taken up, the Plugin is for Deep Dungeon, not for outside Deep Dungeon... Shouldn't even show anything outside of a DD imo

Right now we have to disable the whole plugin when we are not in a DD

(Making a new post as there is no response for the comments in the initial post after closing it)

### Steps to reprduce

Targeting any mob not inside a deep dungeon. Happens with target dummies as well.

### Environment

```markdown
- **OS**:
- **Dalamud**:
```

### Anything else?

See also issue #168

**Comment by yrusabu** [comment]
I am having the same issue. The window with the mob information appears outside deep dungeon.

**Comment by KyonKyonxox** [comment]
I don't see the added value as all this does outside of Deep Dungeon is show an error, and give us a link to open an issue about it here. 
At the absolute least, please give us a way to disable it.

**Comment by wolfcomp** [comment]
Intended feature as of 2.9.0

**Comment by KyonKyonxox** [comment]
Disappointing.

בתאריך יום ו׳, 12 בינו׳ 2024, 02:26, מאת wolfcomp ***@***.***
