### ISSUE TITLE
[Bug]: Data issue pop-up outside of DD content

### ISSUE THREAD

**Issue by ladyredxiv** [wolfcomp/DeepDungeonDex#179]
### Dalamud log

None

### Steps to reprduce

Target mob OUTSIDE of DD content

### Environment

```markdown
- **OS**: Windows 11
- **Dalamud**: 9.0.0.14
```

### Anything else?

![image](https://github.com/wolfcomp/DeepDungeonDex/assets/9207909/83fa79ed-dca1-4546-9155-4c85fea22d76)
![image](https://github.com/wolfcomp/DeepDungeonDex/assets/9207909/445ca20c-65a0-42e2-ac80-487173703ca9)

**Comment by wolfcomp** [comment]
Duplicate #173
