### ISSUE TITLE
F91-100 

### ISSUE THREAD

**Issue by AdagioFantasque** [wolfcomp/DeepDungeonDex#186]
### Mob Id

0 - Orthodrone

### Content Type

TreasureHuntDungeon

### What threat level sould the mob have

Easy

### What agro type does the mob have

Sight

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

### Additional mob text guide

Auto-cannons : line aoe
Self-Detonate on death, explodes in aoe radius like Ice Sprites from F41+

**Comment by wolfcomp** [comment]
No valid id supplied
