### ISSUE TITLE
Add mimic info

### ISSUE THREAD

**Issue by XTayuun** [wolfcomp/DeepDungeonDex#187]
### Mob Id

0 - Mimic

### Content Type

TreasureHuntDungeon

### What threat level sould the mob have

Dangerous

### What agro type does the mob have

Proximity

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

### Additional mob text guide

Casts accursed pox which gives a heavy 10 minute DOT. Deathtrap is a quick AOE with high one-shot potential. 
Bronze mimic: Can interrupt pox cast with silence/stun/knockback/witching/interject
Silver mimic: Can interrupt pox cast with stun/witching/interject
Gold mimic: Can only interrupt pox cast with interject/witching

**Comment by wolfcomp** [comment]
Mimics uses widely different ids from the different ones in the game. If there are specific ones that doesn't have info I need their respective ids in a separate post for each one rather than a general post about what each do.
