### ISSUE TITLE
Can't install through the dalamud pluginlist

### ISSUE THREAD

**Issue by Duckeah** [wolfcomp/DeepDungeonDex#49]
After clicking install it gets stuck for a min and then nothing happens

**Comment by Duckeah** [comment]
![Animation](https://user-images.githubusercontent.com/80353971/183531212-b9b50a22-5e10-4cf8-a1aa-720afb60800d.gif)

**Comment by Strati** [comment]
In-game, if you open the plugin log with /xllog then try to install the plugin, do you get an error in the log?

**Comment by Duckeah** [comment]
![image](https://user-images.githubusercontent.com/80353971/183628571-95b7d35b-e680-4174-92a2-fe44d93219d2.png)
[xxllogs.txt](https://github.com/wolfcomp/DeepDungeonDex/files/9289649/xxllogs.txt)
Here

**Comment by wolfcomp** [comment]
Dalamud issue. Possibly related to specific AV not wanting to let Dalamud download the code.
