### ISSUE TITLE
[Fix]: Data for

### ISSUE THREAD

**Issue by ShaunJS** [wolfcomp/DeepDungeonDex#58]
### Mob Id

[several, see report]

### Vulnerabilities for the enemy

- [ ] Stun
- [ ] Heavy
- [ ] Slow
- [X] Sleep
- [ ] Bind
- [ ] Undead

### Additional mob text guide

Unfortunately I couldn't determine the mob id, I tried looking for an online database and couldn't find any lists of monsters that showed IDs, perhaps I missed something obvious, or a plugin, etc. Please let me know how I can do this so I can help out >_<; 

Sleep seems to be reported incorrectly (or perhaps simply the data was never collected?) for most mobs. Happy to try and test/collect this data if I can figure out Mob ids as it's extremely useful data for BLM (et al) solo climbers.

Some examples for reference:
![2](https://user-images.githubusercontent.com/13086676/189549663-7c245fce-3415-4594-bb77-3f6d67009683.png)
![1](https://user-images.githubusercontent.com/13086676/189549667-3d429a53-3c26-44e5-989d-d46aef620fc2.png)
![3](https://user-images.githubusercontent.com/13086676/189549669-db6dce4e-c3c8-4929-b8e9-ca9f0fd7c98c.png)

**Comment by wolfcomp** [comment]
If you can retake the screenshots of the UI with the new version with `Show debug information` enabled it will list out the id.
