### ISSUE TITLE
[Fix]: Data for Heavenly Morbol, 61-70, add Slow

### ISSUE THREAD

**Issue by KyonKyonxox** [wolfcomp/DeepDungeonDex#73]
### Mob Id

40012F97

### Vulnerabilities for the enemy

- [X] Stun
- [ ] Heavy
- [X] Slow
- [ ] Sleep
- [ ] Bind
- [ ] Undead

**Comment by KyonKyonxox** [comment]
Slow tested as WAR, through Arm's Length. The following mobs are also affected by Slow but aren't marked right in the plugin:

Heavenly Jellyfish - 40012FA0
Heavenly Penghou - 40013490
Heavenly Kosodegai - 4001348C
Heavenly Chizakura - 4001348F
Heavenly Shitaibana - 40013485

**Comment by wolfcomp** [comment]
Please provide the correct ids using [this](https://github.com/wolfcomp/DeepDungeonDex/issues/58#issuecomment-1247160443) method

**Comment by KyonKyonxox** [comment]
I'll be blunt, you're asking for a LOT. I wiped on floor 89 so sure, I'm
going in again, but it's already a lot of work to get to those floorsets
and you don't have a way of telling which mobs these are other than "do it
again with this flag turned on"?
That's really making it difficult for people to contribute. Don't you have
logs somewhere I can check, or a mapping between the ACT IDs and your IDs?

**Comment by KyonKyonxox** [comment]
Actually, I take that back. I'm running it solo, so I don't have the capacity to keep track of the mob ID and which effect actually worked on the mob.
If you have logs saved somewhere I can look up after the fact, I'd be happy to contribute. If not, would it be possible to have the debug option print the data to an in-game stream?
