### ISSUE TITLE
[Bug]: Bestiary does not appear

### ISSUE THREAD

**Issue by Flavescent** [wolfcomp/DeepDungeonDex#88]
### Dalamud log

09:12:51.675 | ERR Unobserved exception in Task.
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at DeepDungeonDex.Requests.Language.ChangeLanguage() in /work/repo/DeepDungeonDex/Requests/Language.cs:line 43
   at DeepDungeonDex.Requests.Language.RefreshLang(Boolean continuous) in /work/repo/DeepDungeonDex/Requests/Language.cs:line 105
   --- End of inner exception stack trace ---

### Steps to reprduce

Install the plugin, enter POTD

### Environment

```markdown
- **OS**:Windows 10
- **Dalamud**: up to date as of report
```

### Anything else?

The bestiary does not appear, nor do I find any documentation on how to make it appear (in a separate window? in the chat log on mob targeting? holding a hotkey?)

**Comment by wolfcomp** [comment]
If you enable `Testing` for the plugin. Hopefully within a day it should get a new version that might fix this. If not, I added more logging to figure out what is actually causing this issue.

If it fails setting languages, it will not load the bestiary due to how I tried to do some optimizations with the compact view.

**Comment by wolfcomp** [comment]
Seems to be fixed with 2.3.0 which will hit live after 6.3 comes out
